{{- if .Values.secrets.peer.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: fabric-logger--{{ .Values.peer.orgDomain | lower }}--{{ .Values.peer.peerName  | lower }}-msp
  labels:
    orgDomain: {{ .Values.peer.orgDomain }}
    peerName: {{ .Values.peer.peerName }}
data:
  cert.pem: |-
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/users/%s@%s/msp/signcerts/%s@%s-cert.pem" .Values.peer.orgDomain .Values.peer.username .Values.peer.orgDomain .Values.peer.username .Values.peer.orgDomain ) | b64enc }}
  tlscacert.pem: |- 
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/users/%s@%s/msp/tlscacerts/tlsca.%s-cert.pem" .Values.peer.orgDomain .Values.peer.username .Values.peer.orgDomain .Values.peer.orgDomain ) | b64enc }}
  {{- range $path, $bytes := $.Files.Glob (printf "crypto-config/peerOrganizations/%s/users/%s@%s/msp/keystore/*" .Values.peer.orgDomain .Values.peer.username .Values.peer.orgDomain ) }}
  key.pem: |-
      {{ $.Files.Get $path | b64enc }}
  {{- end }}
{{- end}}